version: '3.3'
services:
  db:
    image: 'mysql:8'
    restart: always
    environment:
      '0': MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'my-db:/var/lib/mysql'
volumes:
  my-db: null
